DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  name VARCHAR(20)
);

INSERT OR IGNORE INTO users(id,name) VALUES(1,'Dupond');
SELECT name FROM users;
DELETE FROM users WHERE id=1;

